Repository Workiva/slate, pull requests merged in 2018-08, with the labels that each got.

#18 CEREBRAL-602 Release slate 2.2.5
  VERSION.md
Labels: Hold Auto-Merge, Merge Requirements Met, RM Ready

#19 CEREBRAL-607 Add simple skynet test.
  docker-compose-skynet.yml
  skynet.yaml
  tool/integration.sh
Labels: Hold Auto-Merge, Merge Requirements Met

#20 CEREBRAL-617 Release slate 2.2.7
  VERSION.md
Labels: Hold Auto-Merge, Merge Requirements Met, RM Ready

#26 RM-32837 RM-32836 CEREBRAL-620 Release slate 2.2.8
  VERSION.md
Labels: Hold Auto-Merge, Merge Requirements Met, RM Ready

#30 RM-33450 RM-33449 CEREBRAL-692 Release slate 2.2.9
  VERSION.md
Labels: Hold Auto-Merge, Merge Requirements Met, RM Ready

#32 RM-33539 RM-33538 CEREBRAL-704 Add empty npm.lock to satisify rm.
  Dockerfile
Labels: Hold Auto-Merge, Merge Requirements Met

#33 RM-33557 RM-33556 CEREBRAL-705 Release slate 2.2.12
  VERSION.md
Labels: Hold Auto-Merge, Merge Requirements Met, RM Ready

#34 Consume cerebral v1.0.80
  VERSION.md
Labels: Merge Requirements Met, RM Ready

#35 Consume cerebral v1.0.81
  VERSION.md
Labels: Merge Requirements Met, RM Ready
