Repository Workiva/slate, pull requests merged in 2018-07, with the labels that each got.

#5 Add vscode to gitignore.
  .gitignore
  Dockerfile
  VERSION.md
Labels: Merge Requirements Met

#7 Release slate 1.0.1
  VERSION.md
Labels: Merge Requirements Met

#8 Release slate 1.0.2
  VERSION.md
Labels: Merge Requirements Met

#9 Release slate 2.2.1
  VERSION.md
Labels: Merge Requirements Met

#10 CEREBRAL-579 Split to includes
  .gitignore
  Dockerfile
  source/includes/_authentication.md
  source/includes/_errors.md
  source/includes/_workflows.md
  source/index.html.md
Labels: Hold Auto-Merge, Merge Requirements Met

#13 CEREBRAL-590 Release slate 2.2.3
  VERSION.md
Labels: Hold Auto-Merge, Merge Requirements Met, RM Ready
